name: ads_challenge
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_svg: ^1.1.5
  shared_preferences: ^2.1.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0
  pinput: ^2.2.12
  webview_flutter: ^2.0.14
  flutter_slidable: ^2.0.0
  readmore: ^2.2.0
  curved_navigation_bar: ^1.0.3 
  flutter_zoom_drawer: ^2.1.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/home/
    - assets/detail/
    - assets/cart/
    - assets/checkout/
    - assets/auth/
    - assets/profile/
    - assets/splash/
    - assets/onboarding/
  

